#!/bin/sh
set -e

cargo build
cargo build --examples
cargo test

echo "Entering bitbox02-api-wasm for wasm-pack"
(cd bitbox02-api-wasm/ || exit; wasm-pack build; wasm-pack test --node)

echo "Entering bitbox02-api-c/examples/unlock for make"
(cd bitbox02-api-c/examples/unlock || exit; make)
