[target.x86_64-apple-darwin]
linker = "x86_64-apple-darwin21.4-clang"
ar = "x86_64-apple-darwin21.4-ar"

[target.aarch64-apple-darwin]
linker = "aarch64-apple-darwin21.4-clang"
ar = "aarch64-apple-darwin21.4-ar"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
